### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by skelder** [Yipin/Dance_Dance_Generation#2]
Hello,

Is there any additional steps I have to do before running the training command?

I downloaded the pytorch mula weights and placed them into the pretrained-weights folder.

However When I run the train command I get error during dataset load

`CustomDatasetDataLoader

dataset [AlignedDataset] was created

Traceback (most recent call last):
  File "train.py", line 41, in <module>
    data_loader = CreateDataLoader(opt)
  File "C:\Dance_Dance_Generation\data\data_loader.py", line 6, in CreateDataLoader
    data_loader.initialize(opt)
  File "C:\Dance_Dance_Generation\data\custom_dataset_data_loader.py", line 20, in initialize
    self.dataset = CreateDataset(opt)
  File "C:\Dance_Dance_Generation\data\custom_dataset_data_loader.py", line 11, in CreateDataset
    dataset.initialize(opt)
  File "C:\Dance_Dance_Generation\data\preprocess_dataset.py", line 44, in initialize
    self.A_paths = sorted(make_dataset(self.dir_A))
  File "C:\Dance_Dance_Generation\data\image_folder.py", line 24, in make_dataset
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: \Personal_dataset\train_videos\trans_segs is not a valid directory`

I guess I have to do some processing with pix2pix code before running the train command?

I am trying this on Windows 10 environment with conda based python 3.7.

**Comment by Yipin** [comment]
Hi, this code requires some pre-processing data as the training data (e.g. transformed segments from target person, pose representation ... etc). Unfortunately we have not included this part yet but will stay tuned. But feel free to generate according training data based on the instruction in the code.

**Comment by Yipin** [comment]
Hi, this code requires some pre-processing data as the training data (e.g. transformed segments from target person, pose representation ... etc). Unfortunately we have not included this part yet but will stay tuned. But feel free to generate training data from any youtube videos based on the instruction in the code.
